apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: 049820221501.dkr.ecr.us-east-1.amazonaws.com/sonal/sonal:orders
        ports:
        - containerPort: 80
